import { IObserver } from "./marshaling";
import { ObjectInfo, Position, Region, AltitudeType, VehicleInfo, WeaponStatus, RelationsState, SensorType, VehicleOnBoard, GeoPosition } from "./types";
export type ServerMethods = {
    RegisterClient(params: {
        name: string;
    }): boolean;
    GetPackages(params: {}): Map<string, string>;
    GetClients(): Array<string>;
    NotifyClient(params: {
        target: string;
        payload: any;
    }): void;
    MessageClient(params: {
        target: string;
        payload: any;
    }): any;
    GetPackage(params: {
        selector: string;
    }): string;
    GetCurrentTime(params: {}): number;
    GetTaskforces(): Array<string>;
    GetUnitsInTaskforce(params: {
        taskforce: string;
    }): Array<number>;
    GetObjectInfo(params: {
        unitid: number;
    }): ObjectInfo;
    HasFlightDeck(params: {
        unitid: number;
    }): boolean;
    GetAircraftOnFlightDeck(params: {
        unitid: number;
    }): Array<VehicleOnBoard>;
    LaunchAircraft(params: {
        unitid: number;
        aircraftName: string;
        loadoutName: string;
    }): number;
    GoToWaypoint(params: {
        unitid: number;
        lat: number;
        lon: number;
    }): void;
    ClearWaypoints(params: {
        unitid: number;
    }): void;
    GoToPosition(params: {
        unitid: number;
        position: Position;
        altitude?: number;
        altitudeType?: AltitudeType;
    }): void;
    WatchArea(params: {
        taskforce: string;
        region: Region;
        vehicleObserver: IObserver<VehicleInfo>;
    }): void;
    VehiclesInArea(params: {
        taskforce: string;
        region: Region;
    }): Array<VehicleInfo>;
    UnitDestroyed(params: {
        unitid: number;
    }): void;
    WaitGameTime(params: {
        delay: number;
    }): void;
    GetUnitPosition(params: {
        unitid: number;
    }): GeoPosition;
    OnTrigger(params: {
        triggerName: string;
    }): void;
    FireTrigger(params: {
        triggerName: string;
    }): void;
    WatchState(params: {
        unitid: number;
        orderObserver: IObserver<string>;
    }): void;
    NotifyWinchester(params: {
        unitid: number;
    }): void;
    GetHomeBase(params: {
        unitid: number;
    }): GeoPosition;
    AttackVehicle(params: {
        unitid: number;
        vehicleid: number;
    }): void;
    SetWeaponPosture(params: {
        unitid: number;
        posture: WeaponStatus;
    }): void;
    GetWeaponPosture(params: {
        unitid: number;
    }): WeaponStatus;
    ForceVehicleRelation(params: {
        vehicleid: number;
        relation: RelationsState;
    }): void;
    IsRelationForced(params: {
        vehicleid: number;
    }): boolean;
    ClearForcedRelation(params: {
        vehicleid: number;
    }): boolean;
    SetEMCON(params: {
        unitid: number;
    }): void;
    SetSensorEnabled(params: {
        unitid: number;
        sensorType: SensorType;
        enabled: boolean;
    }): void;
};
export type ClientMethods = {
    echo(params: {
        message: string;
    }): string;
    Exec(params: Array<{
        actionName: string;
        context: any;
        parameters: string;
    }>): Promise<boolean>;
    Save(params: {}): string;
    Load(params: {
        payload: string;
    }): boolean;
    RecvMessage(params: {
        sender: string;
        payload: any;
    }): any;
};
